name: Nya Nya Nya

on:
  schedule:
    - cron: "0 0 * * *" # 每天早八撸一次猫 =w=
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get-food:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Get Files
        run: |
          set -e
          curl -O https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
          curl -O https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt

      - name: Upload gfw-raw.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gfw-raw-artifact
          path: ./gfw.txt
          retention-days: 1

      - name: Upload proxy-raw.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy-raw-artifact
          path: ./proxy.txt
          retention-days: 1

  nya-1:
    needs: get-food # 明确依赖关系
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.12"

      - name: Download gfw-raw.txt
        uses: actions/download-artifact@v4
        with:
          name: gfw-raw-artifact
          path: ./
      
      - name: Download proxy-raw.txt
        uses: actions/download-artifact@v4
        with:
          name: proxy-raw-artifact
          path: ./

      - name: Make keywords.txt
        run: |
          set -e
          python3 -u ./scripts/keywords.py keywords.txt

      - name: Upload keywords.txt
        uses: actions/upload-artifact@v4
        with:
          name: keywords-artifact
          path: ./keywords.txt
          retention-days: 1

      - name: Process and rename gfw.txt
        run: |
          set -e
          mv gfw.txt gfw-raw.txt
          python3 -u ./scripts/simplify.py gfw-raw.txt
          mv gfw-raw.txt gfw.txt

      - name: Process and rename proxy.txt
        run: |
          set -e
          mv proxy.txt proxy-raw.txt
          python3 -u ./scripts/simplify.py proxy-raw.txt
          mv proxy-raw.txt proxy.txt

      - name: Upload processed gfw.txt
        uses: actions/upload-artifact@v4
        with:
          name: gfw-processed-artifact
          path: ./gfw.txt
          retention-days: 1

      - name: Upload processed proxy.txt
        uses: actions/upload-artifact@v4
        with:
          name: proxy-processed-artifact
          path: ./proxy.txt
          retention-days: 1

  nya-2:
    needs: [get-food, nya-1]
    runs-on: ubuntu-latest
    steps:
      - name: Generate release tag
        id: tag
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Checkout repository for release branch
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Download processed gfw.txt
        uses: actions/download-artifact@v4
        with:
          name: gfw-processed-artifact
          path: ./ # 确保下载到根目录

      - name: Download processed proxy.txt
        uses: actions/download-artifact@v4
        with:
          name: proxy-processed-artifact
          path: ./

      - name: Download keywords.txt
        uses: actions/download-artifact@v4
        with:
          name: keywords-artifact
          path: ./

      - name: Check files existence
        run: |
          ls -la gfw.txt
          ls -la keywords.txt
          ls -la proxy.txt

      - name: Update release branch
        run: |
          git checkout -B release
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gfw.txt keywords.txt proxy.txt
          git commit -m "Update release files [skip ci]"
          git push origin release --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          files: |
            gfw.txt
            proxy.txt
            keywords.txt
          draft: false
          prerelease: false
